use std::{env, sync::LazyLock};

use axum::{routing::get, Router};
use chrono::{Duration, Local, Timelike, Utc};
use gemini_rust::{Gemini, Model};
use hypertext::prelude::*;
use miniflux_api::{
    models::{EntryStatus, OrderBy, OrderDirection},
    MinifluxApi,
};
use reqwest::Client;
use tokio::sync::Mutex;
use url::Url;

const SYSTEM: &str = "
You are the user's highly capable Personal Press Secretary.
Your goal is to provide a concise, sophisticated, and engaging editorial briefing.

# Tone and Style:
- Professional yet conversational (think 'The Economist' meets a high-end personal assistant).
- Group related stories into narrative themes rather than just listing them.
- Use 'You' to address the user.
- Highlight *why* a story matters.
- Avoid repetitive bullet points; use short, punchy paragraphs.

# Structure:
1. A brief, warm greeting based on the current time (Morning/Evening).
2. 'The Big Story' - The most impactful trend or news item of the day.
3. 'Other Notable Developments' - Grouped by theme.
4. 'A Quick Look Ahead' - A one-sentence closing thought.

# Constraints:
- Use Markdown for clear headers and bold text.
- Maintain the original 'Read More' links but weave them naturally or place them at the end of sections.
";

const MODEL: Model = Model::Gemini3Flash;

type CachedSummary = (chrono::DateTime<Local>, String);

static SUMMARY_CACHE: LazyLock<Mutex<Option<CachedSummary>>> = LazyLock::new(|| Mutex::new(None));

fn md_to_html(md: &str) -> String {
    let parser = pulldown_cmark::Parser::new(md);
    let mut html = String::new();
    pulldown_cmark::html::push_html(&mut html, parser);
    html
}

fn wrap_in_layout(inner_html: &str) -> String {
    let page = rsx! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>"Personal Press Briefing"</title>
                <style>
                    "body { font-family: 'Georgia', serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 0 20px; background-color: #fdfdfd; }"
                    "h1, h2, h3 { color: #900; border-bottom: 1px solid #eee; padding-bottom: 10px; }"
                    "blockquote { border-left: 4px solid #900; padding-left: 20px; font-style: italic; color: #555; }"
                    ".container { background: white; padding: 40px; box-shadow: 0 2px 15px rgba(0,0,0,0.05); }"
                    "a { color: #900; text-decoration: none; font-weight: bold; }"
                    "a:hover { text-decoration: underline; }"
                </style>
            </head>
            <body>
                <div class="container">
                    <main>
                        ( hypertext::Raw::dangerously_create(inner_html) )
                    </main>
                    <footer style="margin-top: 50px; font-size: 0.8em; color: #777; border-top: 1px solid #eee; padding-top: 20px;">
                        "Generated by " (MODEL.to_string()) " • " ( Local::now().format("%Y-%m-%d %H:%M").to_string() )
                    </footer>
                </div>
            </body>
        </html>
    };

    page.render().into_inner()
}

async fn get_rss_data() -> (String, Vec<i64>) {
    // 1. Initialize the client for megumu
    // The domain is rss.kamoshi.org as defined in your Nix configuration
    let url = Url::parse("https://rss.kamoshi.org").unwrap();

    let api_token = env::var("TOKEN_MINIFLUX").unwrap_or_default();
    if api_token.is_empty() {
        return ("MINIFLUX_API_TOKEN is not set".to_string(), vec![]);
    }

    let api = MinifluxApi::new_from_token(&url, api_token);

    let http_client = Client::new();

    // Calculate the Unix timestamp for 2 days ago
    let two_days_ago = (Utc::now() - Duration::days(2)).timestamp();

    // 2. Fetch entries using a parameterized query
    // Parameters: status, offset, limit, order, direction, before, after, etc.
    let entries = api
        .get_entries(
            Some(EntryStatus::Unread),  // Filter only unread
            None,                       // offset
            Some(20),                   // limit
            Some(OrderBy::PublishedAt), // order
            Some(OrderDirection::Desc), // direction
            None,                       // before
            Some(two_days_ago),         // after: entries published since this timestamp
            None,                       // before_entry_id
            None,                       // after_entry_id
            None,                       // starred
            &http_client,
        )
        .await;

    let entries = match entries {
        Ok(e) => e,
        Err(err) => return (format!("Failed to fetch entries: {:?}", err), vec![]),
    };

    let entry_ids: Vec<i64> = entries.iter().map(|e| e.id).collect();

    // 3. Process the results
    let mut output = String::new();
    for entry in entries {
        output.push_str(&format!(
            "Title: {}\nPublished at: {}\nURL: {}\n\n{}\n\n===\n\n",
            entry.title, entry.published_at, entry.url, entry.content
        ));
    }

    if output.is_empty() {
        ("No unread entries found.".to_string(), vec![])
    } else {
        (output, entry_ids)
    }
}

async fn summary() -> impl axum::response::IntoResponse {
    let mut cache = SUMMARY_CACHE.lock().await;
    let now = Local::now();

    if let Some((cached_time, cached_result)) = &*cache {
        // Shift time back by 6 hours so the natural 12-hour halves (AM/PM) align exactly with [06:00, 18:00) and [18:00, 06:00)
        let c = *cached_time - Duration::hours(6);
        let n = now - Duration::hours(6);

        if c.date_naive() == n.date_naive() && (c.hour() / 12) == (n.hour() / 12) {
            return axum::response::Html(cached_result.clone());
        }
    }

    let api_key = env::var("TOKEN_GEMINI").unwrap_or_default();
    if api_key.is_empty() {
        return axum::response::Html(wrap_in_layout("TOKEN_GEMINI is not set"));
    }

    let client = match Gemini::with_model(api_key, MODEL) {
        Ok(c) => c,
        Err(e) => {
            return axum::response::Html(wrap_in_layout(&format!("Failed to create client: {}", e)))
        }
    };

    let (data, entry_ids) = get_rss_data().await;

    let time = Local::now().format("%Y-%m-%d %H:%M").to_string();
    let data =
        format!("Current time: {time}\nI have the following articles from RSS tracker: {data}");

    let result = match client
        .generate_content()
        .with_system_instruction(SYSTEM)
        .with_user_message(data)
        .with_max_output_tokens(4096)
        .with_temperature(0.7)
        .with_top_p(0.9)
        .with_top_k(40)
        .execute()
        .await
    {
        Ok(response) => {
            if !entry_ids.is_empty() {
                let url = Url::parse("https://rss.kamoshi.org").unwrap();
                let api_token = env::var("TOKEN_MINIFLUX").unwrap_or_default();
                if !api_token.is_empty() {
                    let api = MinifluxApi::new_from_token(&url, api_token);
                    let http_client = Client::new();
                    let _ = api
                        .update_entries_status(entry_ids, EntryStatus::Read, &http_client)
                        .await;
                }
            }
            response.text()
        }
        Err(e) => return axum::response::Html(wrap_in_layout(&format!("Error: {}", e))),
    };

    let html_content = md_to_html(&result);
    let styled_page = wrap_in_layout(&html_content);

    *cache = Some((now, styled_page.clone()));

    axum::response::Html(styled_page)
}

pub fn router() -> Router {
    Router::new().route("/summary", get(summary))
}
